apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-mikrotik-conf
  namespace: monitoreo
data:
  telegraf.conf: |-
    [agent]
      interval = "20s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "20s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      hostname = ""
      omit_hostname = false
    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "mikrotik"
      exclude_database_tag = false
      skip_database_creation = false
      username = "influxuser"
      password = "influxPasw0rld"
    [[inputs.snmp]]
      agents = ["udp://192.168.1.1:161"]
      timeout = "4s"
      community = "lacofradia"
      # Authentication
      version = 3
      sec_name = "lacofradia"
      auth_protocol = "MD5"
      auth_password = "unodostres"
      sec_level = "authPriv"
      priv_protocol = "DES"
      priv_password = "unodostres"
      [[inputs.snmp.field]]
        oid = "iso.3.6.1.4.1.14988.1.1.3.10.0"
        name = "temp"
      [[inputs.snmp.field]]
        oid = "1.3.6.1.2.1.25.2.3.1.6.65536"
        name = "ram-use"
      [[inputs.snmp.field]]
        oid = "1.3.6.1.2.1.25.2.3.1.5.65536"
        name = "ram-max"
      [[inputs.snmp.field]]
        oid = "1.3.6.1.2.1.25.3.3.1.2.1"
        name = "cpu-utilization"
      [[inputs.snmp.field]]
        oid = "iso.3.6.1.2.1.25.1.1.0"
        name = "uptime"
      [[inputs.snmp.field]]
        oid = "1.3.6.1.4.1.14988.1.1.3.14.0"
        name = "voltage"
      [[inputs.snmp.table]]
        name = "interfaces"
        inherit_tags = ["hostname"]
        [[inputs.snmp.table.field]]
          name = "if-name"
          oid = ".1.3.6.1.2.1.2.2.1.2"
          is_tag = true
        [[inputs.snmp.table.field]]
          name = "mac-address"
          oid = ".1.3.6.1.2.1.2.2.1.6"
          is_tag = true
          conversion = "hwaddr"
        [[inputs.snmp.table.field]]
          name = "actual-mtu"
          oid = ".1.3.6.1.2.1.2.2.1.4"
        [[inputs.snmp.table.field]]
          name = "admin-status"
          oid = ".1.3.6.1.2.1.2.2.1.7"
        [[inputs.snmp.table.field]]
          name = "oper-status"
          oid = ".1.3.6.1.2.1.2.2.1.8"
        [[inputs.snmp.table.field]]
          name = "bytes-in"
          oid = ".1.3.6.1.2.1.31.1.1.1.6"
        [[inputs.snmp.table.field]]
          name = "packets-in"
          oid = ".1.3.6.1.2.1.31.1.1.1.7"
        [[inputs.snmp.table.field]]
          name = "discards-in"
          oid = ".1.3.6.1.2.1.2.2.1.13"
        [[inputs.snmp.table.field]]
          name = "errors-in"
          oid = ".1.3.6.1.2.1.2.2.1.14"
        [[inputs.snmp.table.field]]
          name = "bytes-out"
          oid = ".1.3.6.1.2.1.31.1.1.1.10"
        [[inputs.snmp.table.field]]
          name = "packets-out"
          oid = ".1.3.6.1.2.1.31.1.1.1.11"
        [[inputs.snmp.table.field]]
          name = "discards-out"
          oid = ".1.3.6.1.2.1.2.2.1.19"
        [[inputs.snmp.table.field]]
          name= "errors-out"
          oid= ".1.3.6.1.2.1.2.2.1.20"
      [[inputs.snmp.table]]
        name = "leases-ip"
        inherit_tags = ["hostname"]
        index_as_tag = true
        [[inputs.snmp.table.field]]
          name = "mac"
          oid = "iso.3.6.1.2.1.9999.1.1.6.4.1.8"
          #is_tag = true
          conversion = "hwaddr"
        [[inputs.snmp.table.field]]
          name = "expires-after"
          oid = "iso.3.6.1.2.1.9999.1.1.6.4.1.5"
        [[inputs.snmp.table.field]]
          name = "status"
          oid = "iso.3.6.1.2.1.9999.1.1.6.4.1.7"
