apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-mikrotik
  namespace: monitoreo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-mikrotik
  template:
    metadata:
      name: telegraf-mikrotik
      labels:
        app: telegraf-mikrotik
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
      containers:
      - name: telegraf-mikrotik
        image: quinont/telegraf-snmp:1
        resources:
          limits:
            memory: "1Gi"
            cpu: "600m"
          requests: 
            memory: "500Mi"
            cpu: "400m"
        volumeMounts:
          - mountPath: /etc/telegraf
            name: telegraf-mikrotik-conf
            readOnly: true
      volumes:
        - name: telegraf-mikrotik-conf
          configMap:
              defaultMode: 420
              name: telegraf-mikrotik-conf

