apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-datasources
  namespace: monitoreo
data:
  INFLUXDB_HTTP_AUTH_ENABLED: "true"
  AUTH_ENABLED: "true"
  INFLUXDB_DATA_ENGINE: tsm1
  INFLUXDB_REPORTING_DISABLED: "false"
  INFLUXDB_ADMIN_ENABLED: "true"
  INFLUXDB_DB: mqtt
