kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-storage
  namespace: monitoreo
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
