apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-conf
  namespace: monitoreo
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data/
    log_dest stderr
    log_dest file /mosquitto/log/mosquitto.log
    listener 9001
    protocol websockets
    port 1883
    protocol mqtt
    log_timestamp_format %Y-%m-%dT%H:%M:%S
